# Server configuration
server.port=8080

# Database connection settings
# Thay đổi username và password cho đúng với cấu hình MySQL của bạn trên HeidiSQL nhé
spring.datasource.url=jdbc:mysql://localhost:3306/un1-ecommerce-j2ee?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=0932164734instagram
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate SQL logs configuration
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ddl-auto=update: tự động cập nhật / tạo bảng khi Entities có thay đổi (chạy Spring Boot)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
